version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - '4000:4000'

  client:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_BASE_URL: http://localhost:5000

