version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5433:5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST_DOCKER: db
      NODE_ENV: docker
      DB_USER_DOCKER: ${DB_USER}
      DB_PASSWORD_DOCKER: ${DB_PASSWORD}
      DB_DATABASE_DOCKER: ${DB_DATABASE}
    ports:
      - '4000:4000'
    volumes:
      - ./.env:/app/.env


  client:
    build: ../frontend
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_BASE_URL: http://localhost:4000
